[accesslog]

[api]
  insecure = true
  dashboard = true
  debug = true

[log]
  level = "INFO"

[entryPoints]
  [entryPoints.xavki]
    address = ":3000"

  [entryPoints.websecure]
    address = ":443"
    [entryPoints.websecure.http.tls]

[providers.file]
  directory = "/home/livai/Projects/Node/Microservice/config/"
  watch = true

[tls]
  [[tls.certificates]]
    certFile = "/home/livai/Projects/Node/Microservice/certificates/aro.mg.crt"
    keyFile = "/home/livai/Projects/Node/Microservice/certificates/aro.mg.key"

[providers.docker]
  endpoint = "unix:///var/run/docker.sock"

# Enable metrics collection
[metrics]
  [metrics.prometheus]
    addEntryPointsLabels = true
    addServicesLabels = true
    entryPoint = "metrics" # Optional entry point for Prometheus scraping

# Optional: Add a dedicated entry point for metrics scraping (if needed)
[entryPoints.metrics]
  address = ":8082"




