version: "3.9"

services:
  micro1:
    image: micro1
    ports:
      - "4000:4000"
      - "8000:8000"
    depends_on:
      - postgres
    restart: always

  micro2:
    image: micro2
    ports:
      - "4001:4001"
      - "8001:8001"
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: local
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:


